---
title: "Normatividad Vigente de la UACM"
author: "Carlos Ernesto Martinez"
date: "2023-12-04"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 3
    code_folding: show
    css: styles.css
    theme: united  # many options for theme, this one is my favorite.
    highlight: tango  # specifies the syntax highlighting style
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# [Ley de la Universidad](LeyUACM.html)

# [Estatuto General Orgánico](EGO.html)

# [Reglamento del Consejo Universitario](RCU.html)

# [Lineamientos para Sesiones Virtuales](LineamientosSV.html)

# [Reglamento de Responsabilidades Universitarias](RRUU.html)

# [Reglamento en Materia Electoral](RME.html)

# [Estatuto de la Defensoria de los Derechos Universitarios](EDDU.html)

# [Catálogo de Normas de Convivencia](NormasConvivencia.html)

# [Protocolo para Prevenir y Erradicar la Violencia y la Discriminación contra las Mujeres](Protocolo.html)

# [Marco Estructural del Plan Integral de Desarrollo Institucional](PIDE.html)

# [Reglamento de la Defensoría de los Derechos Universitario](RDDU.html)

# [Lineamientos para la Creación de Nuevas Sedes](LineamientosNuevasSedes.html)

# [Unidad de Transparencia](UnidadTransparencia.html)

# [Norma Cuatro](NormaCuatro.html)

# [Norma de Planeación](NormaPlaneacion.html)

# [Norma de Adquisiciones](NormaAdquisiciones.pdf)
